export const SELECT_USER = "SELECT_USER";

export const RECEIVE_USERS = "RECEIVE_USERS";

export const RECEIVE_ROLES = "RECEIVE_ROLES";

export const RECEIVE_PROJECTS = "RECEIVE_PROJECTS";

export const RECEIVE_USER_PROJECTS = "RECEIVE_USER_PROJECTS";

export const ADD_ROLE_BEGIN = "ADD_ROLE_BEGIN";
export const ADD_ROLE_SUCCESS = "ADD_ROLE_SUCCESS";
export const ADD_ROLE_FAILURE = "ADD_ROLE_FAILURE";

export const REMOVE_ROLE_BEGIN = "REMOVE_ROLE_BEGIN";
export const REMOVE_ROLE_SUCCESS = "REMOVE_ROLE_SUCCESS";

export const CLOSE_ALERT = "CLOSE_ALERT";